apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-exaz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-exaz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-exaz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-exaz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-exaz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zfoj-tenant/rhtap-demo-app/hacbs-test-project-exaz@sha256:d5b618df38e722035a4a818a1cc10bbc7be5656f92ede0b694f3688aac0c48fc
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
